### ISSUE TITLE
Add Paperspace Gradient links to all notebooks

### ISSUE THREAD

**Issue by lewtun** [huggingface/optimum-graphcore#188]
Hi there 👋 !

I'm adding links to all the Graphcore notebooks in the Optimum docs and I noticed that only 3 notebooks have links to run on Paperspace. Any chance we can have links for all notebooks?

![Screen Shot 2022-10-07 at 09 03 47](https://user-images.githubusercontent.com/26859204/194487783-fd10cd6e-49d5-4a07-9298-f50607d816fa.png)

**Comment by jimypbr** [comment]
Thanks! I updated them!

**Comment by lewtun** [comment]
Thanks @jimypbr ! Unfortunately, I'm finding that the new links throw an error - here's what I get for the "Train an external model" link: 

![Screen Shot 2022-10-10 at 17 26 08](https://user-images.githubusercontent.com/26859204/194901670-066863e0-24c0-46d9-8538-9acc0d806f91.png)

Are you able to reproduce this on your end?

**Comment by jimypbr** [comment]
Yes, I'm also getting that. Sorry, I'll investigate again.

**Comment by internetoftim** [comment]
The repo that is passed as argument to the gradient API doesn't contain the notebook you're trying to load, hence the error. For the exernal_model notebook, you pass the API `gradient-ai/Graphcore-HuggingFace` when it should be `huggingface/optimum-graphcore` where you can find `external_model.ipynb`

I'm referring to this in the code:

`| [Train an external model](https://github.com/huggingface/optimum-graphcore/blob/main/notebooks/external_model.ipynb) | Show how to train an external model that is not supported by Optimum or Transformers. | [![Gradient](https://assets.paperspace.io/img/gradient-badge.svg)](https://console.paperspace.com/github/gradient-ai/Graphcore-HuggingFace?machine=Free-IPU-POD16&container=graphcore%2Fpytorch-jupyter%3A2.6.0-ubuntu-20.04-20220804&file=%2Fnotebook-tutorials%2Fexternal_model.ipynb) |`

**Comment by lewtun** [comment]
Thanks @internetoftim for the clarification! I think we need URLs like the following:

```
https://console.paperspace.com/github/huggingface/optimum-graphcore/blob/main/notebooks/external_model.ipynb?container=graphcore%2Fpytorch-jupyter%3A2.6.0-ubuntu-20.04-20220804&Free-IPU-POD16
```

but maybe @jimypbr can check if this truly spins up an IPU

**Comment by jimypbr** [comment]
@lewtun @internetoftim  Hi I've made a PR fixing the links. Can either of you please double-check these are working for you please?
