### ISSUE TITLE
deberta base text multiclasss trainer.trian() Target size (torch.Size([16])) must be the same as input size 

### ISSUE THREAD

**Issue by liygzting** [huggingface/optimum-graphcore#223]
### System Info

```shell
Graphcore instance
import transformers
import optimum.graphcore
print(transformers.__version__)
print(optimum.graphcore.__version__)
4.20.0
0.3.1
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

deberta base text multiclasss trainer.trian() Target size (torch.Size([16])) must be the same as input size 

### Expected behavior

loss func may be the key

**Comment by liygzting** [comment]
Hi @jimypbr  datasets look like this,
![image](https://user-images.githubusercontent.com/73510109/206596750-08d5d69f-e6e0-4596-b46d-549e1cae5bfd.png)

and my code 

`
from transformers import AutoModelForSequenceClassification, default_data_collator
from optimum.graphcore import IPUConfig, IPUTrainer, IPUTrainingArguments

model_name = "microsoft/deberta-base"
num_labels = 273
tokz = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

ipu_config = IPUConfig.from_pretrained("Graphcore/deberta-base-ipu")

# train model
bs = 56
epochs = 5
lr = 2e-4
sn = 1000   

args = IPUTrainingArguments(
    "outputs",
    ipu_config_name="Graphcore/bert-base-ipu",
    evaluation_strategy = "steps",
    eval_steps=sn,
    save_strategy = "steps",
    save_steps=sn,save_total_limit=3,
    learning_rate=lr,
    per_device_train_batch_size=bs,
    per_device_eval_batch_size=bs,
    num_train_epochs=epochs,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    dataloader_drop_last=True,
    logging_steps=sn,
    pod_type="pod16",
    gradient_accumulation_steps=bs,
    push_to_hub=False,
)

from datasets import load_metric
metric = load_metric('accuracy') 

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# Initialize our Trainer
trainer = IPUTrainer(
     model=model,
     ipu_config=ipu_config,
     args=args,
     train_dataset=dds['train'],
     eval_dataset=dds['test'],
    tokenizer=tokz, compute_metrics=compute_metrics
)

trainer.train()

`
then get the error:
/usr/local/lib/python3.8/dist-packages/torch/nn/modules/loss.py in forward(self, input, target)
    702 
    703     def forward(self, input: Tensor, target: Tensor) -> Tensor:
--> 704         return F.binary_cross_entropy_with_logits(input, target,
    705                                                   self.weight,
    706                                                   pos_weight=self.pos_weight,

/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py in binary_cross_entropy_with_logits(input, target, weight, size_average, reduce, reduction, pos_weight)
   2978 
   2979     if not (target.size() == input.size()):
-> 2980         raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
   2981 
   2982     return torch.binary_cross_entropy_with_logits(input, target, weight, pos_weight, reduction_enum)

ValueError: Target size (torch.Size([56])) must be the same as input size (torch.Size([56, 273]))


But, when setting labels  as int , other error is :
Error                                     Traceback (most recent call last)
<ipython-input-35-3435b262f1ae> in <module>
----> 1 trainer.train()

/usr/local/lib/python3.8/dist-packages/optimum/graphcore/trainer.py in train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
    902         self._load_optimizer_and_scheduler(resume_from_checkpoint)
    903 
--> 904         self._compile_model(model, next(iter(train_dataloader)), log=True)
    905 
    906         # Train!

/usr/local/lib/python3.8/dist-packages/optimum/graphcore/trainer.py in _compile_model(self, model, sample_batch, log)
    373             model.compile(*sample_batch)
    374         else:
--> 375             model.compile(**sample_batch)
    376         duration_compilation = time.perf_counter() - start_compile
    377         if log:

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in compile(self, *args, **kwargs)
    750             )
    751         else:
--> 752             self._compile(in_tensors)
    753 
    754     @_impl.traceMethod("loadExecutable")

/usr/local/lib/python3.8/dist-packages/poptorch/_impl.py in wrapper(self, *args, **kwargs)
    286         def wrapper(self, *args, **kwargs):
    287             with self._profiling.tracepoint(label):  # pylint: disable=protected-access
--> 288                 return func(self, *args, **kwargs)
    289 
    290         return wrapper

/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py in _compile(self, in_tensors)
    661         if not self.isCompiled():
    662             if self._options.Jit.trace_model:
--> 663                 self._executable = poptorch_core.compileWithTrace(*trace_args)
    664             else:
    665                 self._executable = self._compileWithDispatch(

Error: In poptorch/poptorch_err/include/poptorch_err/ExceptionHandling.hpp:76: 'popart_exception': Could not find loss tensor 'IdentityLoss:0' in main graph tensors
Error raised in:
  [0] popart::TrainingSession::createFromOnnxModel
  [1] Compiler::initSession
  [2] LowerToPopart::compile
  [3] compileWithTrace

**Comment by jimypbr** [comment]
@liygzting were you able to solve this? Another issue I just noticed is that your optimum-graphcore version is old. I've discovered that there is a bug in our instructions `pip install optimum[graphcore]` which wrongly installs an older version.
Please do `pip install optimum-graphcore --upgrade` to get the latest version (currently 0.4.3)
