### ISSUE TITLE
bert and roberta models

### ISSUE THREAD

**Issue by upunaprosk** [huggingface/optimum-graphcore#402]
Hi, 

[BERT-base](https://huggingface.co/Graphcore/bert-base-ipu/tree/main) and [RoBERTa-base](https://huggingface.co/Graphcore/roberta-base-ipu/tree/main) and most of the other models are not available now (anymore). 
Is it planned to add them soon? Is it possible to use older versions of those?

Cheers,

**Comment by jimypbr** [comment]
Hi! 

What issue are you seeing?
The models on the hub that end with `-ipu` like `bert-base-ipu` and `roberta-base-ipu` are intended only as `IPUConfig` files. The usage is:

```
from optimum.graphcore import IPUConfig
ipu_config = IPUConfig.from_pretrained("Graphcore/roberta-base-ipu")
```

For the weights of the actual model you can use the same weights as you would on CPU or GPU - e.g. `bert-base-uncased`. 
Does this answer your question?

**Comment by jimypbr** [comment]
Yeah it can be initialized with those weights. `Graphcore/bert-large-uncased` is an equivalent version `bert-large-uncased`  that was pretrained on IPU. But either version will work for fine-tuning or inference on IPU.
The "models" on the hub that end with `-ipu` are intended just as IPUConfigs, if you want to use those, though you can  easily create your own if you want customization.
