### ISSUE TITLE
Fix transformers version to match with Graphcore's SDK

### ISSUE THREAD

**Issue by sergiopperez** [huggingface/optimum-graphcore#71]
The Graphcore's SDK is tested for certain versions of `transformers` (at the moment the maximum one is 4.17.0). However, optimum requires the latest version  of `transformers` or otherwise throws an error — see for instance [this line in `examples/question-answering/run_qa.py`](https://github.com/huggingface/optimum-graphcore/blob/main/examples/question-answering/run_qa.py#L53), where it checks for the most recent version:
```
# Will error if the minimal version of Transformers is not installed. Remove at your own risks.
check_min_version("4.18.0.dev0")
```
Is there a way of setting a certain version of transformers in optimum? Ideally we'd like to be able to checkout a certain `transformers` version and not master. Thanks.

**Comment by jimypbr** [comment]
This isn't an issue of what the SDK is compatible with, rather it's whether the scripts should require the latest stable release of `transformers` (which is currently 4.17.0) or if we should require install from master branch of `transformers`. Currently if we install `optimum` it installs 4.17.0 by default and so the scripts fail when you try to run them.
