### ISSUE TITLE
Set more wandb options in training_args.py 

### ISSUE THREAD

**Issue by sergiopperez** [huggingface/optimum-graphcore#72]
It's not clear how to enable wandb logging from optimum. By default it's off, but it can be turned on with the following environment variable: `WANDB_DISABLED=false`. Other envvars [are detailed in this page](https://docs.wandb.ai/guides/integrations/huggingface). Ideally we'd like a `--wandb` in `training_args.py` that enables it. I've noticed that there's already one flag related to wandb in `training_args.py`,[ line 166-168](https://github.com/huggingface/optimum-graphcore/blob/509a9ab0e7a4df09b842a2f445cf3e659f8000bf/optimum/graphcore/training_args.py#L166):

```
run_name: Optional[str] = field(
        default=None, metadata={"help": "An optional descriptor for the run. Notably used for wandb logging."}
    )
```

Could we add two other wandb args? One to enable it (e.g. `wandb`) and another to set the project name (e.g. `project_name`). Thanks.

**Comment by jimypbr** [comment]
Looking at the documentation the way transformers does this is with using environment vairables. We try hard not to diverge from how transformers does things.
