### ISSUE TITLE
Inference speed metrics takes compilation time into account.

### ISSUE THREAD

**Issue by alex-coniasse** [huggingface/optimum-graphcore#96]
- When recording the speed of an inference loop, the `start_time ` used for the speed metrics is recorded before the call to `evaluation_loop` (https://github.com/huggingface/optimum-graphcore/blob/main/optimum/graphcore/trainer.py#L1440).
However, `evaluation_loop` contains the model compilation (`self._wrap_and_compile_model_for_evaluation`) which can be a lot longer than the actual execution time of the evaluation loop. (In the case of training, the compilation occurs before `start_time` is recorded).

- Another thing, the very first call to the dataloader :
`
for step, inputs in enumerate(dataloader):
` 
can take several seconds to start. Again, this can be a lot compared to the actual evaluation loop execution time. (Especially when we have just a few steps to execute). I'm not sure if this should be excluded from the total time as well.

**Comment by jimypbr** [comment]
@michaelbenayoun I agree with you on the second point.
